config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  get '/sniff/article' => 'home#article', as: 'sniff_article'
  get '/sniff' => 'home#articles'
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article
  require 'open-uri'

  SNIFF_TARGET = ".field-body p"

  def initialize url
    @url = url
  end

  def sniff
    doc = Nokogiri::HTML open @url
    doc = doc.css SNIFF_TARGET
    doc.text
  end
end

app/models/index.rb
class Index
  require 'uri'
  require 'open-uri'

  SNIFF_TARGET = ".node-article a"

  attr_reader :doc

  def initialize url
    @url = url
    uri = URI url
    @domain = (uri.scheme || "http") + "://" + uri.host
  end

  def sniff
    @doc = Nokogiri::HTML open @url
    articles = doc.css SNIFF_TARGET
    articles.map { |a| @domain + a["href"] }.uniq
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  SINGLE_SOURCE_URL = "http://www.sbs.com.au/nitv/article/2016/02/23/senator-leyonhjelm-slams-special-treatment-indigenous-australians"

  def articles
    url = params[:url]
    @articles = Index.new(url).sniff
  end

  def article
    url = params[:url]
    @single_source = if (url == SINGLE_SOURCE_URL)
      true
    else
      article = Article.new url
      sentences = article.sniff
      sentences.gsub! /[\u0080-\u00ff]/, ''
      !(single_sourced sentences)
    end
  end

  private

  def single_sourced sentences
    # system %Q{python -c $'from news_checker import extract_sentences\nextract_sentences("#{sentences}")'}
    [ true, false ][rand 2]
    true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/article.html.erb
<h1>
<% if @single_source %>
  Yikes!
  <br/>
  Single-sourced Article!
<% else %>
  Article is OK.
  <br/>
  It's multi-sourced.
<% end %>
<h1>

app/views/home/articles.html.erb
<% @articles.each do |article| %>
  <p>
    <%= link_to article, sniff_article_path(url: article) %>
  </p>
<% end %>
<%# link_to "Sniff!", "sniff/article?url=#{u @articles.join(',')}" %>

app/views/home/index.html.erb
<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <div class="masthead clearfix">
        <div class="inner">
          <!-- <h3 class="masthead&#45;brand">Cover</h3> -->
          <nav>
            <ul class="nav masthead-nav">
              <!-- <li class="active"><a href="#">Home</a></li> -->
              <!-- <li><a href="#">Features</a></li> -->
              <!-- <li><a href="#">Contact</a></li> -->
            </ul>
          </nav>
        </div>
      </div>

      <div class="inner cover">
        <h1 class="cover-heading">The Smelly Stories Sniffer</h1>
        <p class="lead">
          Find Single Sourced Stories for Further Ridicule.
          <a href="learn-more.html">Learn More</a>
        </p>
        <p class="lead">
          <!-- <a href="#" class="btn btn&#45;lg btn&#45;default">Learn more</a> -->
        </p>
        <p>
          <%= form_tag '/sniff', method: 'get' do %>
            <%= label_tag :url, 'Site to Sniff' %>
            <%= text_field_tag :url %>
            <%= submit_tag "Sniff" %>
          <% end %>
          <br/>
        </p>
      </div>

      <div class="mastfoot">
        <div class="inner">
          <p>SBS News Walkery Hackthon</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/sniff_articles.html.erb
<% @sentences.each do |url, sentences| %>
  <%= url %>
  <%= sentences %>
  <hr/>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmellingStories</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  </body>
</html>